name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/aws_key.pem
          chmod 600 ~/.ssh/aws_key.pem

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Deploy to EC2
        run: |
          echo "Deploying to EC2 instance"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/aws_key.pem ubuntu@52.201.95.109 << 'EOF'
            cd /home/ubuntu/mcp-platform  # Correct the directory path
            git pull origin main
            npm install
            pm2 restart mcp-platform  # Replace with your actual PM2 app name
          EOF
